### PR TITLE
Bugfix for Reolink animal detection parsing issues

### PR DESCRIPTION
**Pull request by watkinrt**
=

# Description

The current implementation assumes animal detection information is returned on all GetAiState requests for Reolink cameras; however, not all cameras/NVRs return this information, causing an exception to be thrown during state parsing. This is a bug fix of this issue, adding in a basic check before acting about animal detection information.

# Testing

This pull request has been compiled and tested to work with the following hardware:

* Reolink RLN8-410 NVR (Hardware number N3MB01 with firmware v3.0.0.148_21101146)
* Reolink RLC-810A and RLC-820A cameras

Signed-off-by: Ryan Watkins <watkinrt@gmail.com>

### CODE REVIEW

**Comment by Skinah** [comment]
Thank you for the changes, great and I will look them over AFTER the DCO error is fixed. The DCO just requires that you enter this as the very last line in your commit message AND also in the PR message..

`Signed-off-by: Matthew Skinner <matt@pcmus.com>`

Your name and the email address used by github. If this is not sorted out, it will prevent me from getting the changes merged into the main openHAB github project.

**Comment by watkinrt** [comment]
Sorry about that, this is my first time submitting a pull request that required DCO. I've updated the commits and the PR comment accordingly.

**Comment by Skinah** [comment]
I finally got around to updating this to V4 as it will need to be this to be merged, took some time and some changes may have caused some merge conflicts. My guess is that you did not change 10 files and huge line changes that the review is showing, can you rebase on the recent changes? I did look before moving to V4 and from memory it was only 1-2 lines that you wanted changed, if its easier I may just make the change if that's easier then fixing the merge conflicts?

**Comment by Skinah** [comment]
Added it, as I found what is really a single line change. Thanks for the suggestion.

**Pull request closed without merging**
