### PR TITLE
Adapt itests to new netty release

### PR DESCRIPTION
**Pull request by holgerfriedrich**
This is the output of mvn -DwithResolver. I had to do some changes to pom and java code, as ruuvigateway is currently disabled. But I wanted to include it as well, to ease the fixing of this test.

### CODE REVIEW

**Review by wborn — APPROVED** [review]

**Comment by Skinah** [comment]
Thanks for doing this, do you know why this is needed and if it can be improved to not needing to be done? It creates another level of complexity that will prevent libraries from being kept up to date which is now a necessary evil to do because of security flaws need to be fixed and not ignored in the digital age we now live in. I have updated Netty a couple of times and previously this was not needed, so this must be a recent change.

**Comment by wborn** [comment]
Netty is also a dependency of the Moquette MQTT broker which is used in the MQTT Binding integration tests which got revived with https://github.com/openhab/openhab-addons/pull/12431. The last Netty update was before those changes, see https://github.com/openhab/openhab-addons/pull/11863.

**Comment by holgerfriedrich** [comment]
@Skinah @wborn Hi, how do we proceed with this one? As far as I understood, there is no way around updating the bnd files, since they are required for our integration tests.

I have to touch the corresponding bnd as well to re-enable the last of the itests that got disabled due to changes in core.... My recommendation would be to merge and complete the netty upgrade first.

**Comment by Skinah** [comment]
LGTM. RE my comments, this is not the place to discuss making changes, so lets merge as is.

**Comment by holgerfriedrich** [comment]
@Skinah thanks. I think it is up to you to merge, as I created the PR to your branch.
OH CI will then recompile your branch again.

**Pull request merged**
